Make tags optional for Elements
younata/SwiftOpenStreetMap pull request #1
Opened 2017-09-17 14:49 UTC by aldevet

It turns out basic nodes don't provide tags, therefore they won't get parsed making some ways to not contain their nodes. These changes amend this issue and it also changes the response's nodes and ways to be public rather than have them mixed together in elements.

2017-09-17 15:33 UTC, younata commented
Was curious why that was happening.

2017-09-17 15:43 UTC, younata requested changes
Looks pretty good, just need some tests and this'll be good.

2017-09-17 16:59 UTC, aldevet commented
Added a test for this particular case and modified one to reflect a node without tags. Let me know if you need me to change anything.

2017-09-18 14:25 UTC, younata commented
Thank you!

2017-09-18 14:25 UTC, merged